# Generated by Django 5.0.4 on 2024-04-29 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=45)),
                ('sender_id', models.IntegerField()),
                ('sender_name', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=45)),
                ('sender_location', models.CharField(max_length=45)),
                ('place', models.CharField(max_length=45)),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'Incidents',
            },
        ),
    ]
